"""Header-only C++ protobuf libraries generated by roo_pb."""

load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("@rules_cc//cc/common:cc_info.bzl", "CcInfo")

RooPbInfo = provider(
    doc = "Schema inputs available to downstream roo_pb_library imports.",
    fields = {"sources": "Dict mapping proto import paths and sidecar paths to Files."},
)

def _logical_name(ctx, source):
    if source.owner.package != ctx.label.package or source.owner.workspace_name != ctx.label.workspace_name:
        fail("srcs and options must belong to this package; use deps for other packages")
    path = source.short_path
    if path.startswith("../"):
        path = path.split("/", 2)[2]
    prefix = ctx.label.package + "/" if ctx.label.package else ""
    strip = ctx.attr.strip_import_prefix
    if strip:
        prefix += strip + "/"
    if not path.startswith(prefix):
        fail("%s is outside strip_import_prefix %r" % (source.short_path, strip))
    return path[len(prefix):]

def _roo_pb_library_impl(ctx):
    strip = ctx.attr.strip_import_prefix
    if strip and (strip.startswith("/") or ".." in strip.split("/") or "." in strip.split("/") or "" in strip.split("/")):
        fail("strip_import_prefix must be a normalized package-relative directory")

    sources = {}
    for dep in ctx.attr.deps:
        for name, source in dep[RooPbInfo].sources.items():
            if name in sources and sources[name] != source:
                fail("conflicting proto import path: %s" % name)
            sources[name] = source

    direct = {}
    for source in ctx.files.srcs:
        name = _logical_name(ctx, source)
        if name in sources or name in direct:
            fail("duplicate proto import path: %s" % name)
        direct[name] = source
    sources.update(direct)
    for source in ctx.files.options:
        name = _logical_name(ctx, source)
        if name[:-len(".roo_pb.toml")] + ".proto" not in direct:
            fail("sidecar %s has no matching source in srcs" % name)
        if name in sources:
            fail("duplicate sidecar: %s" % name)
        sources[name] = source

    outputs = []
    if direct:
        # A virtual import tree makes imports independent of repository/package
        # layout. Sidecars stay adjacent to their schema, as the compiler expects.
        inputs = []
        input_dir = ctx.label.name + "_imports"
        for name, source in sources.items():
            linked = ctx.actions.declare_file(input_dir + "/" + name)
            ctx.actions.symlink(output = linked, target_file = source)
            inputs.append(linked)
        import_root = inputs[0].path[:-len(sources.keys()[0])].rstrip("/")
        output_dir = ctx.label.name + "_generated"
        for name in direct:
            outputs.append(ctx.actions.declare_file(output_dir + "/" + name[:-6] + ".pb.h"))
        output_root = outputs[0].path[:-len(direct.keys()[0][:-6] + ".pb.h")].rstrip("/")
        args = ctx.actions.args()
        args.add(ctx.file._compiler.path)
        args.add_all(["--direct-only", "-I", import_root, "--out", output_root])
        args.add_all(direct.keys())
        ctx.actions.run_shell(
            command = 'exec python3 "$@"',
            arguments = [args],
            inputs = depset(inputs),
            tools = [ctx.file._compiler] + ctx.files._compiler_sources,
            outputs = outputs,
            mnemonic = "RooPbCompile",
            progress_message = "Generating roo_pb headers for %{label}",
            use_default_shell_env = True,
        )
        own_cc = CcInfo(compilation_context = cc_common.create_compilation_context(
            headers = depset(outputs),
            includes = depset([output_root]),
        ))
    else:
        own_cc = CcInfo()

    return [
        DefaultInfo(files = depset(outputs, transitive = [dep[DefaultInfo].files for dep in ctx.attr.deps])),
        RooPbInfo(sources = sources),
        cc_common.merge_cc_infos(cc_infos = [own_cc, ctx.attr._runtime[CcInfo]] + [dep[CcInfo] for dep in ctx.attr.deps]),
    ]

roo_pb_library = rule(
    implementation = _roo_pb_library_impl,
    doc = "Generates C++17 headers and exposes a C++ library with the roo_pb runtime. Requires host Python 3.11+.",
    attrs = {
        "srcs": attr.label_list(allow_files = [".proto"], doc = "Schemas in this package. Import paths are package-relative after stripping strip_import_prefix."),
        "options": attr.label_list(allow_files = [".roo_pb.toml"], doc = "Sidecars beside srcs; list explicitly so configuration changes trigger regeneration."),
        "deps": attr.label_list(providers = [RooPbInfo, CcInfo], doc = "Other roo_pb_library targets whose schemas are imported. Empty srcs creates an aggregate library."),
        "strip_import_prefix": attr.string(doc = "Package-relative directory removed from schema import and generated header paths."),
        "_compiler": attr.label(default = Label("//:tools/generate.py"), allow_single_file = True, cfg = "exec"),
        "_compiler_sources": attr.label(default = Label("//:compiler_sources"), cfg = "exec"),
        "_runtime": attr.label(default = Label("//:roo_pb"), providers = [CcInfo]),
    },
    provides = [CcInfo, RooPbInfo],
)
