[platformio]
default_envs = roo, nanopb
build_dir = ../../build/esp32_benchmark/pio

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
build_type = release
build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++2a -std=gnu++2b -fexceptions
build_flags = -std=gnu++17 -Os -fno-lto
extra_scripts = pre:build.py

[env:roo]
build_flags = ${env.build_flags} -DPROTO_BENCH_ROO

[env:nanopb]
build_flags = ${env.build_flags} -DPROTO_BENCH_NANOPB -DPB_BUFFER_ONLY -DPB_VALIDATE_UTF8
