// Generated by roo_pbc 0.1.0. Do not edit.
#pragma once

#include "roo_pb/message.h"

namespace example {

/// Owned protobuf value; borrowed callback bindings survive Clear().
class Device {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 204;

  /// Creates a message initialized to schema defaults.
  Device() : has_name_(0) {}

  /// Destroys active oneof values and their owned resources.
  ~Device() { clear_state(); }

  /// Copies owned values and borrowed callback bindings from @p other.
  Device(const Device& other) : Device() { *this = other; }

  /// Copies values and bindings; self-assignment leaves the message unchanged.
  Device& operator=(const Device& other) {
    if (this == &other) {
      return *this;
    }
    id_ = other.id_;
    name_ = other.name_;
    has_name_ = other.has_name_;
    readings_ = other.readings_;
    clear_state();
    switch (other.state_case_) {
      case 4:
        ::new (static_cast<void*>(&online_)) bool(other.online_);
        break;
      case 5:
        ::new (static_cast<void*>(&reason_))::roo_pb::BoundedString<64>(
            other.reason_);
        break;
      default:
        break;
    }
    state_case_ = other.state_case_;
    return *this;
  }

  /// Moves owned values and borrowed callback bindings from @p other.
  Device(Device&& other) noexcept : Device() { *this = std::move(other); }

  /// Moves values and bindings; self-assignment leaves the message unchanged.
  Device& operator=(Device&& other) noexcept {
    if (this == &other) {
      return *this;
    }
    id_ = std::move(other.id_);
    name_ = std::move(other.name_);
    has_name_ = other.has_name_;
    readings_ = std::move(other.readings_);
    clear_state();
    switch (other.state_case_) {
      case 4:
        ::new (static_cast<void*>(&online_)) bool(std::move(other.online_));
        break;
      case 5:
        ::new (static_cast<void*>(&reason_))::roo_pb::BoundedString<64>(
            std::move(other.reason_));
        break;
      default:
        break;
    }
    state_case_ = other.state_case_;
    return *this;
  }

  /// Identifies the active alternative in state.
  enum class StateCase : uint32_t {
    kNotSet = 0,
    kOnline = 4,
    kReason = 5,
  };

  /// Returns the active oneof alternative.
  StateCase state_case() const { return static_cast<StateCase>(state_case_); }

  /// Destroys the active value and clears selection; callback bindings survive.
  void clear_state() {
    switch (state_case_) {
      case 4: {
        using Value = bool;
        online_.~Value();
        break;
      }
      case 5: {
        using Value = ::roo_pb::BoundedString<64>;
        reason_.~Value();
        break;
      }
      default:
        break;
    }
    state_case_ = 0;
  }

  /// Returns the current field value or its schema default.
  const uint32_t& id() const { return id_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_id(uint32_t value) { id_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_id() { id_ = 0; }

  /// Returns the current field value or its schema default.
  const ::roo_pb::BoundedString<32>& name() const { return name_; }

  /// Reports explicit field presence.
  bool has_name() const { return has_name_; }

  /// Assigns bytes without changing the field on capacity failure.
  bool try_set_name(const char* value, size_t size) {
    ::roo_pb::BoundedString<32> temporary;
    if (!temporary.assign(value, size)) {
      return false;
    }
    has_name_ = true;
    name_ = std::move(temporary);
    return true;
  }

  /// Assigns a NUL-terminated string, reporting capacity failure.
  bool try_set_name(const char* value) {
    return value != nullptr && try_set_name(value, std::strlen(value));
  }

  /// Assigns bytes; capacity is a release-checked precondition.
  void set_name(const char* value, size_t size) {
    ::roo_pb::Require(try_set_name(value, size));
  }

  /// Assigns a NUL-terminated string with checked capacity.
  void set_name(const char* value) { ::roo_pb::Require(try_set_name(value)); }

  /// Marks the field present and returns mutable owned storage.
  ::roo_pb::BoundedString<32>* mutable_name() {
    has_name_ = true;
    return &name_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_name() {
    name_.clear();
    has_name_ = false;
  }

  /// Returns the number of live elements.
  size_t readings_size() const { return readings_.size(); }

  /// Returns a checked indexed element.
  const int32_t& readings(size_t index) const { return readings_[index]; }

  /// Returns the resident repeated container.
  const ::roo_pb::BoundedArray<int32_t, 16>& readings() const {
    return readings_;
  }

  /// Returns mutable repeated storage; callers must respect bounds.
  ::roo_pb::BoundedArray<int32_t, 16>* mutable_readings() { return &readings_; }

  /// Returns a mutable checked indexed element.
  int32_t* mutable_readings(size_t index) { return &readings_[index]; }

  /// Appends a default element or returns nullptr on capacity failure.
  int32_t* try_add_readings() { return readings_.add(); }

  /// Appends a default element; capacity is a release-checked precondition.
  int32_t* add_readings() {
    int32_t* result = try_add_readings();
    ::roo_pb::Require(result != nullptr);
    return result;
  }

  /// Appends a value, reporting capacity failure.
  bool try_add_readings(const int32_t& value) {
    return readings_.push_back(value);
  }

  /// Appends a value; capacity is a release-checked precondition.
  void add_readings(const int32_t& value) {
    ::roo_pb::Require(try_add_readings(value));
  }

  /// Replaces an indexed element; the index must be valid.
  void set_readings(size_t index, const int32_t& value) {
    readings_[index] = value;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_readings() { readings_.clear(); }

  /// Returns the current field value or its schema default.
  const bool& online() const {
    if (has_online()) {
      return online_;
    }
    static const bool default_value{false};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_online() const { return state_case_ == 4; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_online(bool value) {
    if (state_case_ != 4) {
      clear_state();
      ::new (static_cast<void*>(&online_)) bool{false};
      state_case_ = 4;
    }
    online_ = value;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_online() {
    if (has_online()) {
      clear_state();
    }
  }

  /// Returns the current field value or its schema default.
  const ::roo_pb::BoundedString<64>& reason() const {
    if (has_reason()) {
      return reason_;
    }
    static const ::roo_pb::BoundedString<64> default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_reason() const { return state_case_ == 5; }

  /// Assigns bytes without changing the field on capacity failure.
  bool try_set_reason(const char* value, size_t size) {
    ::roo_pb::BoundedString<64> temporary;
    if (!temporary.assign(value, size)) {
      return false;
    }
    if (state_case_ != 5) {
      clear_state();
      ::new (static_cast<void*>(&reason_))::roo_pb::BoundedString<64>{};
      state_case_ = 5;
    }
    reason_ = std::move(temporary);
    return true;
  }

  /// Assigns a NUL-terminated string, reporting capacity failure.
  bool try_set_reason(const char* value) {
    return value != nullptr && try_set_reason(value, std::strlen(value));
  }

  /// Assigns bytes; capacity is a release-checked precondition.
  void set_reason(const char* value, size_t size) {
    ::roo_pb::Require(try_set_reason(value, size));
  }

  /// Assigns a NUL-terminated string with checked capacity.
  void set_reason(const char* value) {
    ::roo_pb::Require(try_set_reason(value));
  }

  /// Marks the field present and returns mutable owned storage.
  ::roo_pb::BoundedString<64>* mutable_reason() {
    if (state_case_ != 5) {
      clear_state();
      ::new (static_cast<void*>(&reason_))::roo_pb::BoundedString<64>{};
      state_case_ = 5;
    }
    return &reason_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_reason() {
    if (has_reason()) {
      clear_state();
    }
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() {
    clear_id();
    clear_name();
    clear_readings();
    clear_state();
  }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) {
        return input.status();
      }
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kUint32)) {
            input.skip(tag);
            break;
          }
          uint32_t item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kUint32>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) {
            return input.status();
          }
          set_id(item);
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kString)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kString>(input, name_);
          if (input.status() != ::roo_pb::Status::kOk) {
            return input.status();
          }
          has_name_ = true;
          break;
        }
        case 3: {
          if (::roo_pb::GetWireType(tag) ==
              ::roo_pb::WireType::kLengthDelimited) {
            size_t length = 0;
            if (input.length(length) != ::roo_pb::Status::kOk) {
              return input.status();
            }
            auto packed = input.child(length);
            while (packed.status() == ::roo_pb::Status::kOk &&
                   packed.remaining() != 0) {
              int32_t item{};
              ::roo_pb::ReadValue<::roo_pb::Kind::kSint32>(packed, item);
              if (packed.status() != ::roo_pb::Status::kOk) {
                return packed.status();
              }
              int32_t* added = readings_.add();
              if (added == nullptr) {
                return packed.fail(::roo_pb::Status::kCapacity);
              }
              *added = std::move(item);
            }
          } else {
            if (::roo_pb::GetWireType(tag) !=
                ::roo_pb::GetWireType(::roo_pb::Kind::kSint32)) {
              input.skip(tag);
              break;
            }
            int32_t item{};
            ::roo_pb::ReadValue<::roo_pb::Kind::kSint32>(input, item);
            if (input.status() != ::roo_pb::Status::kOk) {
              return input.status();
            }
            int32_t* added = readings_.add();
            if (added == nullptr) {
              return input.fail(::roo_pb::Status::kCapacity);
            }
            *added = std::move(item);
          }
          break;
        }
        case 4: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kBool)) {
            input.skip(tag);
            break;
          }
          bool item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kBool>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) {
            return input.status();
          }
          set_online(item);
          break;
        }
        case 5: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kString)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::BoundedString<64> item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kString>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) {
            return input.status();
          }
          *mutable_reason() = std::move(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) {
      return output.status();
    }
    if (has_reason()) {
      ::roo_pb::WriteField<::roo_pb::Kind::kString>(output, 5, reason_);
    }
    if (output.status() != ::roo_pb::Status::kOk) {
      return output.status();
    }
    if (has_online()) {
      ::roo_pb::WriteField<::roo_pb::Kind::kBool>(output, 4, online_);
    }
    if (output.status() != ::roo_pb::Status::kOk) {
      return output.status();
    }
    ::roo_pb::WriteRepeated<::roo_pb::Kind::kSint32>(output, 3, readings_,
                                                     true);
    if (output.status() != ::roo_pb::Status::kOk) {
      return output.status();
    }
    if (has_name()) {
      ::roo_pb::WriteField<::roo_pb::Kind::kString>(output, 2, name_);
    }
    if (output.status() != ::roo_pb::Status::kOk) {
      return output.status();
    }
    if (id_ != 0) {
      ::roo_pb::WriteField<::roo_pb::Kind::kUint32>(output, 1, id_);
    }
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  uint32_t state_case_ = 0;
  // Only the selected alternative has a live object in this storage.
  union {
    bool online_;
    ::roo_pb::BoundedString<64> reason_;
  };
  uint32_t id_{0};
  ::roo_pb::BoundedString<32> name_{};
  ::roo_pb::BoundedArray<int32_t, 16> readings_{};
  // Grouped presence bits; oneof presence uses its case discriminator.
  uint8_t has_name_ : 1;
};

}  // namespace example
